services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - '80:80'
    container_name: app_nginx
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: _docker/php/Dockerfile
    volumes:
      - ./:/var/www/
    depends_on:
      - mysql
    container_name: app_php

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'laravel'
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
    container_name: app_mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '9090:80'
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    container_name: app_pma

  redis:
      image: redis:latest
      container_name: app_redis
      ports:
          - "6379:6379"
      volumes:
          - redis_data:/data
      command: redis-server --appendonly yes
      restart: always

volumes:
  db:
  redis_data:
